from importlib.metadata import version

import pytest

from examples import click_greeter, click_subcommand

from .test_shtab import no_log_info  # noqa: F401, pylint: disable=unused-import, yapf: disable
from .test_shtab import fix_shell

ARG_HELP = version('click') >= '8.5'


@pytest.fixture
def runner():
    pytest.importorskip('click')
    from click import testing
    return testing.CliRunner()


@fix_shell
def test_plain(shell, runner):
    result = runner.invoke(click_greeter.greeter)
    assert result.output == "Casper says 'hai!' to Anon\n"
    assert result.exit_code == 0
    result = runner.invoke(click_greeter.greeter, ['--print-completion', shell])
    assert "# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab" in result.output
    assert result.exit_code == 0


@fix_shell
def test_rootcmd(shell, runner):
    result = runner.invoke(click_subcommand.main, ['greeter', '--path', '.'])
    assert result.output == "Casper says 'hai!' to Anon after reading from None and .\n"
    assert result.exit_code == 0
    result = runner.invoke(click_subcommand.main, ['completion', shell])
    assert "# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab" in result.output
    assert result.exit_code == 0
